<?php
/**
 * CreateEmailCampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailvio API Reference
 *
 * Mailvio provides a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/KVSocial/mailvio-api  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@mailvio.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateEmailCampaignTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateEmailCampaign
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateEmailCampaignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreateEmailCampaign"
     */
    public function testCreateEmailCampaign()
    {

    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {

    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "html_content"
     */
    public function testPropertyHtmlContent()
    {

    }

    /**
     * Test attribute "html_url"
     */
    public function testPropertyHtmlUrl()
    {

    }

    /**
     * Test attribute "template_id"
     */
    public function testPropertyTemplateId()
    {

    }

    /**
     * Test attribute "scheduled_at"
     */
    public function testPropertyScheduledAt()
    {

    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {

    }

    /**
     * Test attribute "reply_to"
     */
    public function testPropertyReplyTo()
    {

    }

    /**
     * Test attribute "to_field"
     */
    public function testPropertyToField()
    {

    }

    /**
     * Test attribute "recipients"
     */
    public function testPropertyRecipients()
    {

    }

    /**
     * Test attribute "attachment_url"
     */
    public function testPropertyAttachmentUrl()
    {

    }

    /**
     * Test attribute "inline_image_activation"
     */
    public function testPropertyInlineImageActivation()
    {

    }

    /**
     * Test attribute "mirror_active"
     */
    public function testPropertyMirrorActive()
    {

    }

    /**
     * Test attribute "footer"
     */
    public function testPropertyFooter()
    {

    }

    /**
     * Test attribute "header"
     */
    public function testPropertyHeader()
    {

    }

    /**
     * Test attribute "utm_campaign"
     */
    public function testPropertyUtmCampaign()
    {

    }

    /**
     * Test attribute "params"
     */
    public function testPropertyParams()
    {

    }

    /**
     * Test attribute "send_at_best_time"
     */
    public function testPropertySendAtBestTime()
    {

    }

    /**
     * Test attribute "ab_testing"
     */
    public function testPropertyAbTesting()
    {

    }

    /**
     * Test attribute "subject_a"
     */
    public function testPropertySubjectA()
    {

    }

    /**
     * Test attribute "subject_b"
     */
    public function testPropertySubjectB()
    {

    }

    /**
     * Test attribute "split_rule"
     */
    public function testPropertySplitRule()
    {

    }

    /**
     * Test attribute "winner_criteria"
     */
    public function testPropertyWinnerCriteria()
    {

    }

    /**
     * Test attribute "winner_delay"
     */
    public function testPropertyWinnerDelay()
    {

    }

}
