<?php
/**
 * RequestContactImportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailvio API Reference
 *
 * Mailvio provides a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/KVSocial/mailvio-api  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@mailvio.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RequestContactImportTest Class Doc Comment
 *
 * @category    Class */
// * @description RequestContactImport
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestContactImportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RequestContactImport"
     */
    public function testRequestContactImport()
    {

    }

    /**
     * Test attribute "file_url"
     */
    public function testPropertyFileUrl()
    {

    }

    /**
     * Test attribute "file_body"
     */
    public function testPropertyFileBody()
    {

    }

    /**
     * Test attribute "list_ids"
     */
    public function testPropertyListIds()
    {

    }

    /**
     * Test attribute "notify_url"
     */
    public function testPropertyNotifyUrl()
    {

    }

    /**
     * Test attribute "new_list"
     */
    public function testPropertyNewList()
    {

    }

    /**
     * Test attribute "email_blacklist"
     */
    public function testPropertyEmailBlacklist()
    {

    }

    /**
     * Test attribute "sms_blacklist"
     */
    public function testPropertySmsBlacklist()
    {

    }

    /**
     * Test attribute "update_existing_contacts"
     */
    public function testPropertyUpdateExistingContacts()
    {

    }

    /**
     * Test attribute "empty_contacts_attributes"
     */
    public function testPropertyEmptyContactsAttributes()
    {

    }

}
